In [455]:
import numpy as np

##**Задание 1**
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк
и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6,
8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean

In [456]:
a = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [457]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

##**Задание 2**
Вычислите массив a_centered, отняв от значений массива “а” средние значения
соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно
производиться в одно действие. Получившийся массив должен иметь размер 5x2

In [458]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

##**Задание 3**
Найдите скалярное произведение столбцов массива a_centered. В результате должна
получиться величина _centered_spa. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [459]:
_centered_spa = a_centered[:, 0] @ a_centered[:, 1]
_centered_spa

8.0

In [460]:
_centered_spa = np.dot(a_centered[:, 0], a_centered[:, 1])
_centered_spa

8.0

In [461]:
N = a.shape[0]
N
_centered_spa / (N-1)

2.0

##**Задание 4****  
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:  


[Выборочная ковариация и выборочная дисперсия — Студопедия](https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html)

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [462]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

##**Тема “Работа с данными в Pandas”**

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со
столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и
['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно
содержатся данные:
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники']
Нужны prices!
[500, 400, 300, 350, 450, 600, 200]

In [463]:
import pandas as pd

In [464]:
a1 = {'author_id': [1, 2, 3], 'author_name' : ['Тургенев', 'Чехов', 'Островский']}
authors = pd.DataFrame(a1)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [465]:
a2 = {'author_id': [1, 1, 1, 2, 2, 3, 3],
      'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
      'price': [500, 400, 300, 350, 450, 600, 200]}
books = pd.DataFrame(a2)
books

author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200

**Задание 2**  
Получите датафрейм authors_price, соединив дата фреймы authors и books по полю author_id.

In [466]:
authors_price = pd.merge(authors, books, on='author_id', how='inner' ).copy()
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200

**Задание 3**  
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [467]:
top5 = authors_price.nlargest(5, 'price').copy()
top5

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

##**Задание 4**
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:  
author_name, min_price, max_price и mean_price,  
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [468]:
authors_stat = authors_price.groupby('author_name')

In [469]:
authors_stat_max = authors_stat.agg({'price': 'max'}).rename(columns={'price':'max_price'})
authors_stat_max

max_price
author_name           
Островский         600
Тургенев           500
Чехов              450

In [470]:
authors_stat_min = authors_stat.agg({'price': 'min'}).rename(columns={'price':'min_price'})
authors_stat_min

min_price
author_name           
Островский         200
Тургенев           300
Чехов              350

In [471]:
authors_stat_mean = authors_stat.agg({'price': 'mean'}).rename(columns={'price':'mean_price'})
authors_stat_mean

mean_price
author_name            
Островский        400.0
Тургенев          400.0
Чехов             400.0

In [472]:
authors_stat = pd.merge(authors_stat_max, authors_stat_min, on='author_name')
authors_stat = pd.merge(authors_stat, authors_stat_mean, on='author_name').reset_index().copy()
authors_stat

author_name  max_price  min_price  mean_price
0  Островский        600        200       400.0
1    Тургенев        500        300       400.0
2       Чехов        450        350       400.0

In [473]:
# Альтернативный способ
authors_stat_2 = authors_price.groupby('author_name')
authors_stat_new = authors_stat_2.agg({'price': 'max'}).rename(columns={'price':'max_price'})
authors_stat_new

max_price
author_name           
Островский         600
Тургенев           500
Чехов              450

In [474]:
authors_stat_new["min_price"] = authors_stat_2["price"].min()
authors_stat_new['nean_price'] = authors_stat_2["price"].mean()
authors_stat_new.reset_index()

author_name  max_price  min_price  nean_price
0  Островский        600        200       400.0
1    Тургенев        500        300       400.0
2       Чехов        450        350       400.0

##**Задание 5****
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:  
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].  

Просмотрите документацию по функции pd.pivot table с помощью вопросительного знака. Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,
при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны

In [475]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    500  твердая
1          1    Тургенев                 Рудин    400   мягкая
2          1    Тургенев     Дворянское гнездо    300   мягкая
3          2       Чехов      Толстый и тонкий    350  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    600   мягкая
6          3  Островский  Таланты и поклонники    200   мягкая

In [476]:
?pd.pivot_table

In [477]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'] , columns=['cover'], aggfunc=np.sum).fillna(1)
book_info

cover        мягкая  твердая
author_name                 
Островский    800.0      1.0
Тургенев      700.0    500.0
Чехов           1.0    800.0

In [478]:
book_info.to_pickle("book_info.pk")
book_info2 = pd.read_pickle("book_info.pk")
book_info2

cover        мягкая  твердая
author_name                 
Островский    800.0      1.0
Тургенев      700.0    500.0
Чехов           1.0    800.0